[tox]
envlist = py310, py311, py312
skipsdist = True

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312

[testenv]
usedevelop = true
deps =
    requests
    pytest
    responses
    furl
    tiktoken
    pandas
    numpy
    pyarrow
commands = python -m pytest
